apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: Python aoo displays time named ${{values.app_name}}
  annotations:
    github.com/project-slug: eduaran1/${{values.app_name}}
spec:
  type: serice
  lifecycle: experimental
  owner: development